package com.moradipass;

import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

public class PasswordEntry {
    private int id; // NEW: Database ID
    private final StringProperty site;
    private final StringProperty username;
    private final StringProperty password;

    // Constructor for new entries (ID will be generated by DB)
    public PasswordEntry(String site, String username, String password) {
        this.id = -1; // Indicate a new entry
        this.site = new SimpleStringProperty(site);
        this.username = new SimpleStringProperty(username);
        this.password = new SimpleStringProperty(password);
    }

    // Constructor for entries loaded from DB (with an ID)
    public PasswordEntry(int id, String site, String username, String password) {
        this.id = id;
        this.site = new SimpleStringProperty(site);
        this.username = new SimpleStringProperty(username);
        this.password = new SimpleStringProperty(password);
    }

    // NEW: Getter and Setter for ID
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }


    public String getSite() { return site.get(); }
    public String getUsername() { return username.get(); }
    public String getPassword() { return password.get(); }

    public void setSite(String site) { this.site.set(site); }
    public void setUsername(String username) { this.username.set(username); }
    public void setPassword(String password) { this.password.set(password); }

    public StringProperty siteProperty() { return site; }
    public StringProperty usernameProperty() { return username; }
    public StringProperty passwordProperty() { return password; }
}